name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZGVkYzA2MTQtZmI4OS00NjVmLWI2NTQtODhiODA4YzRhNTE3IiwidGVuYW50X2lkIjoiYWQ1ODMyMmJiMThiZWNiMGI0MGY5NzE3ZjJhMWRjMTYxNDRmMzg2YzYxZTgzNGQwZDgzODY0OWFjYzJiMGEzMSIsImludGVybmFsX3NlY3JldCI6ImVhZWJhZDdkLTk1NTctNDNmNC04OTRiLTZmYmNjZWYzZTgzNCJ9.GtiWn-ukqkrE5b3VJ0l1UEcYCgzHOIQbDbClBUoNFDg"

JWT_SECRET = "secret-key"


GOOGLE_CLIENT_ID = 'Ov23ctWxf7EdMSRwEDY5'
GOOGLE_CLIENT_SECRET = '94b717ed7727f5349be3b4f019beb4634d566561'
GITHUB_CLIENT_ID = 'Ov23ctWxf7EdMSRwEDY5'
GITHUB_CLIENT_SECRET = '09d9cf7f68e8c2283a7d0bb15696d375023954f6'